/**
 * COPY del módulo MARKETPLACE — local al módulo (no toca src/lib/i18n/*).
 * Español cálido, mismo tono que VIVIENDA/DIRECTORIOS. Un producto es un
 * `listing` kind='product'; la tienda es el `listing` kind='business' dueño.
 */
export const COPY = {
  list: {
    title: "Marketplace",
    subtitle: "Productos de las tiendas de tu comunidad",
    publishCta: "Publicar producto",
    categoryFilterLabel: "Filtrar por categoría",
    categoryAll: "Todas",
    searchLabel: "Buscar productos en el marketplace",
    searchPlaceholder: "Buscá un producto…",
    searchSubmitLabel: "Buscar",
    searchClearLabel: "Borrar búsqueda",
    loadMore: "Ver más productos",
    emptyTitle: "Todavía no hay productos",
    emptyMessage:
      "Cuando las tiendas de la comunidad publiquen productos, los vas a ver acá. ¿Tenés un negocio? Sé el primero en mostrar lo que vendés.",
    emptyFilteredTitle: "Nada por acá con esa categoría",
    emptyFilteredMessage:
      "Probá con otra categoría o mirá todos los productos disponibles.",
    emptySearchTitle: (q: string) => `No encontramos nada con "${q}"`,
    emptySearchMessage: "Probá con otra palabra o mirá las categorías de arriba.",
    emptyPublishCta: "Publicar mi primer producto",
    viewProduct: "Ver producto",
    storeLinkLabel: (name: string) => `Tienda ${name}`,
    ownerBanner: {
      title: "Tu tienda llega primero a quienes ya te siguen",
      body: "Lo que publicás orgánicamente lo ven tus seguidores. Para llegar a más gente de la comunidad, impulsá tus productos desde su página.",
    },
  },
  detail: {
    priceLabel: "Precio",
    categoryLabel: "Categoría",
    conditionLabel: "Estado",
    descriptionTitle: "Descripción",
    storeTitle: "Vendido por",
    visitStore: "Ver tienda",
    communityMember: "Miembro de la comunidad",
    pendingBanner:
      "Tu producto está en revisión — lo publicamos apenas pase el control de seguridad.",
    boostCta: "Impulsar este producto",
    boostHint: "Llegá a más gente con tu producto, no solo a tus seguidores.",
    galleryLabel: "Fotos del producto",
    galleryPrev: "Foto anterior",
    galleryNext: "Foto siguiente",
    photoCounter: (current: number, total: number) => `${current}/${total}`,
    followersLoading: "Seguidores",
  },
  store: {
    notFoundNudge: "Volvé al marketplace",
    productsTitle: "Productos de esta tienda",
    emptyProductsTitle: "Todavía no publicó productos",
    emptyProductsMessage: "Esta tienda todavía no tiene productos publicados — volvé pronto.",
    followStore: "Seguir tienda",
    followingStore: "Siguiendo",
  },
  publish: {
    title: "Publicar un producto",
    subtitle: "Sumalo a la vidriera de tu tienda en un par de minutos.",
    needLoginTitle: "Para publicar, primero entrá",
    needLoginMessage:
      "Publicar es gratis. Necesitamos que entres a tu cuenta para asociar el producto a tu tienda.",
    needLoginCta: "Entrar a mi cuenta",
    needStoreTitle: "Todavía no tenés una tienda",
    needStoreMessage:
      "Para publicar productos primero necesitás un negocio publicado en la comunidad. Se crea en un par de minutos.",
    needStoreCta: "Crear mi negocio",
    storeFieldLabel: "¿Desde qué tienda publicás?",
    storeFieldHelp: "Elegí el negocio dueño de este producto.",
    titleLabel: "Título del producto",
    titlePlaceholder: "Ej.: Zapatillas deportivas talla 9",
    titleHelp: "Corto y claro — es lo primero que se ve.",
    descriptionLabel: "Descripción",
    descriptionPlaceholder: "Contá el estado, medidas, colores disponibles, lo que sirva para decidir…",
    descriptionHelp: "Mientras más completa, menos preguntas repetidas.",
    priceLabel: "Precio",
    pricePlaceholder: "25",
    categoryLabel: "Categoría",
    categoryPlaceholder: "Elegí una categoría…",
    conditionLegend: "Estado del producto",
    conditionNew: "Nuevo",
    conditionUsed: "Usado",
    photosTitle: "Fotos del producto",
    photosHelp: "Hasta 4 fotos. Los productos con fotos reciben muchas más consultas.",
    addPhotoLabel: "Agregar foto",
    removePhotoLabel: "Quitar foto",
    tooManyPhotos: "Podés subir hasta 4 fotos.",
    tooBigPhoto: "Esa foto es muy pesada — probá con una de menos de 8 MB.",
    reviewNote: "Las fotos pasan por un control de seguridad antes de publicarse.",
    submit: "Publicar producto",
    submitting: "Publicando…",
    errors: {
      storeRequired: "Elegí desde qué tienda publicás.",
      titleShort: "El título necesita al menos 8 caracteres.",
      descriptionShort: "Contanos un poco más sobre el producto.",
      priceRequired: "Poné un precio para tu producto.",
      categoryRequired: "Elegí una categoría.",
      conditionRequired: "Decinos si es nuevo o usado.",
      uploadFailed: "No pudimos subir las fotos — revisá tu conexión e intentá de nuevo.",
      generic: "Algo no cargó bien de nuestro lado — no es tu culpa. Probá de nuevo en un ratito.",
    },
    success: {
      publishedTitle: "¡Tu producto ya está publicado!",
      publishedBody: "Tus seguidores ya pueden verlo en la tienda.",
      reviewTitle: "Tu producto está en revisión",
      reviewBody: "Lo publicamos apenas pase el control de seguridad. Te avisamos por acá.",
      goToStore: "Ver mi tienda",
      goToMarketplace: "Ver marketplace",
      publishAnother: "Publicar otro producto",
    },
  },
} as const;
