import type { ContractStatus, ContractStep } from "./contract-machine";

const GENERIC_ERROR = "Algo no salió bien de nuestro lado — no es tu culpa. Probá de nuevo en un ratito.";

export const STATUS_COPY = {
  proposed: "Propuesta",
  accepted: "Pendiente de firmas",
  signed: "Pendiente de pago",
  funded: "En progreso",
  delivered: "Entregado",
  changes_requested: "En revisión",
  approved: "Pago aprobado",
  released: "Pago liberado",
  canceled: "Cancelado",
  disputed: "En disputa",
  rejected: "Rechazada",
} satisfies Record<ContractStatus, string>;

export const STEP_COPY = {
  propuesta: "Propuesta",
  contrato: "Contrato",
  trabajo: "Trabajo",
  revision: "Revisión",
  pago: "Pago",
} satisfies Record<ContractStep, string>;

export const FLOW_COPY = {
  generic: GENERIC_ERROR,
  back: "Volver",
  proposal: {
    title: "Propuesta formal",
    deliverables: "Entregables",
    delivery: "Fecha de entrega",
    deliveryValue: (days: number) => (days === 1 ? "1 día después del pago" : `${days} días después del pago`),
    revisions: "Revisiones incluidas",
    revisionsValue: (n: number) => (n === 0 ? "Sin revisiones" : n === 1 ? "1 revisión" : `${n} revisiones`),
    usageRights: "Derechos de uso",
    amount: "Monto",
    messageFrom: "Mensaje del negocio",
    accept: "Aceptar propuesta",
    negotiate: "Negociar cambios",
    reject: "Rechazar propuesta",
    acceptHint: "Al aceptar, se genera el contrato de colaboración para que lo firmen los dos.",
    waitingCreator: "Le mandaste la propuesta. Cuando el creador la acepte, se genera el contrato para firmar.",
    edit: "Editar propuesta",
    withdraw: "Retirar propuesta",
    withdrawConfirm: "Vas a retirar la propuesta. El creador ya no la va a poder aceptar.",
    rejectConfirm: "Vas a rechazar esta propuesta. La colaboración se cierra y no se puede reabrir.",
    negotiateTitle: "¿Qué te gustaría cambiar?",
    negotiateHint:
      "Contale al negocio qué ajustarías: monto, plazo, revisiones o derechos de uso. Te avisamos cuando actualice la propuesta.",
    negotiatePlaceholder: "Ej.: Para 4 videos necesito 14 días y un monto de $1,200.",
    lastChangeRequest: "Último pedido de cambios",
    send: "Enviar",
    editTitle: "Editar propuesta",
    save: "Guardar cambios",
    saved: "Propuesta actualizada. Le avisamos al creador.",
    sent: "Listo, le avisamos a la otra parte.",
    accepted: "¡Aceptaste! Ahora falta firmar el contrato.",
    rejected: "Rechazaste la propuesta.",
    withdrawn: "Retiraste la propuesta.",
  },
  signing: {
    title: "Revisar y firmar contrato",
    pending: "Pendiente de ambas firmas",
    signed: "Firmado",
    waiting: "Pendiente",
    you: "Vos",
    client: "Negocio",
    creator: "Creador",
    service: "Servicio",
    delivery: "Entrega",
    revisions: "Revisiones",
    usage: "Derechos de uso",
    cancellation: "Cancelación",
    seeConditions: "Ver condiciones",
    amount: "Monto",
    fullContract: "Ver contrato completo",
    legalName: "Tu nombre legal",
    legalNameHelp: "Nombre y apellido, como figuran en tu documento.",
    signatureLabel: "Tu firma",
    signatureHint: "Dibujá tu firma con el dedo o el mouse.",
    signatureEmpty: "Firmá dentro del recuadro",
    clear: "Borrar",
    consent: "Leí y acepto el contrato y la firma electrónica.",
    submit: "Firmar y aceptar",
    requestChanges: "Solicitar cambios",
    requestChangesHint:
      "El contrato vuelve a propuesta y las firmas se anulan. Contale a la otra parte qué cambiarías.",
    paymentGate: "El pago se habilita cuando firmen las dos partes.",
    youSigned: "Ya firmaste. Falta la firma de la otra parte; te avisamos cuando firme.",
    done: "¡Firmaste el contrato!",
    doneBoth: "¡Contrato firmado por las dos partes!",
    version: (v: number, template: string) => `Versión ${v} · plantilla ${template}`,
    fingerprint: "Huella",
    cancel: "Cancelar colaboración",
    cancelConfirm: "Vas a cancelar la colaboración antes de pagar. No se mueve dinero.",
    signedAt: (when: string) => `Firmado el ${when}`,
  },
  payment: {
    title: "Confirmar pago",
    protected: "Pago protegido",
    workAmount: "Monto del trabajo",
    fee: (pct: number) => `Comisión de la plataforma (${pct}%)`,
    stripeFee: "Procesamiento de Stripe",
    stripeFeeValue: "Incluido",
    creatorGets: "El creador recibe",
    youGet: "Vos recibís",
    explainer:
      "El pago se procesa con Stripe y queda retenido. Se libera al creador cuando apruebes el trabajo o cuando termine el período de revisión.",
    pay: (amount: string) => `Pagar ${amount}`,
    pendingTitle: "Pendiente de pago",
    pending: "El trabajo arranca cuando Stripe confirme el cobro.",
    processing: "Estamos confirmando tu pago con Stripe. Esto tarda unos segundos.",
    canceled: "No se completó el pago. Podés intentarlo de nuevo cuando quieras.",
    creatorWaiting: "El contrato está firmado. Te avisamos apenas el negocio confirme el pago para que arranques.",
    demo: "Modo demostración: no se cobra dinero de verdad.",
    demoDone: "Listo: pago simulado en modo demostración.",
    cardOnly: "Pagás con tarjeta en la página segura de Stripe.",
  },
  work: {
    title: "Trabajo en progreso",
    progress: (pct: number) => `${pct}% completado`,
    workspace: "Espacio de trabajo",
    messages: "Mensajes",
    openChat: "Abrir chat",
    files: "Archivos compartidos",
    contract: "Contrato firmado",
    see: "Ver",
    payment: "Pago protegido",
    paymentConfirmed: "confirmado",
    paymentDemo: "demostración",
    milestonesTitle: "Avance del creador",
    milestonesEmptyCreator:
      "Sumá los pasos de tu trabajo (guion, grabación, edición…) para que el negocio vea cómo vas.",
    milestonesEmptyClient: "El creador todavía no cargó su avance. Lo vas a ver acá paso por paso.",
    addMilestone: "Agregar hito",
    milestonePlaceholder: "Ej.: Guion aprobado",
    milestoneToggle: (title: string, done: boolean) => (done ? `Desmarcar ${title}` : `Marcar ${title} como hecho`),
    finalDelivery: "Entrega final",
    registered: "Todas las conversaciones y entregas quedan registradas acá.",
    deliver: "Entregar trabajo",
    revisionAsked: "El negocio pidió una revisión",
    clientWaiting: "El creador está trabajando. Te avisamos cuando entregue.",
    cancel: "Cancelar y pedir reembolso",
    cancelConfirm:
      "Vas a cancelar antes de la entrega. Te devolvemos el pago completo a tu tarjeta (puede tardar entre 5 y 10 días hábiles).",
  },
  delivery: {
    title: "Entregar trabajo",
    intro: "Subí los archivos finales. El negocio tiene 72 horas para revisarlos; si no responde, el pago se libera solo.",
    pick: "Elegir archivos",
    pickHint: "Video, foto, audio, PDF o ZIP. Hasta 10 archivos de 200 MB cada uno.",
    note: "Mensaje para el negocio",
    notePlaceholder: "Ej.: Acá van los 4 videos. El tercero tiene dos versiones de música.",
    uploading: (done: number, total: number) => `Subiendo ${done} de ${total}…`,
    submit: "Entregar",
    done: "¡Entregado! El negocio ya puede revisarlo.",
    remove: (name: string) => `Quitar ${name}`,
    uploadFailed: (name: string) => `No se pudo subir ${name}. Probá de nuevo.`,
    tooMany: "Podés entregar hasta 10 archivos por vez.",
    badType: (name: string) => `${name} no se puede entregar: usá video, foto, audio, PDF o ZIP de hasta 200 MB.`,
  },
  review: {
    title: "Revisar entrega",
    files: "Archivos entregados",
    view: "Ver",
    opening: "Abriendo…",
    messageFrom: "Mensaje del creador",
    timeLeft: "Tiempo para revisar",
    timeHint: "Después, el pago se libera automáticamente.",
    expired: "El período de revisión terminó. El pago se está liberando.",
    approve: (amount: string) => `Aprobar y liberar ${amount}`,
    approveConfirm: (amount: string) =>
      `Vas a aprobar la entrega y liberar ${amount} al creador. Confirmá sólo si el trabajo está bien.`,
    requestRevision: "Solicitar revisión",
    revisionsLeft: (left: number, total: number) => `${left} de ${total} disponibles`,
    noRevisionsLeft: "Ya usaste las revisiones incluidas.",
    revisionTitle: "¿Qué hay que ajustar?",
    revisionPlaceholder: "Ej.: En el segundo video, cambiá la música y acortá el final.",
    revisionSent: "Le pedimos la revisión al creador. El reloj de 72 horas se pausa hasta la nueva entrega.",
    dispute: "Abrir disputa",
    disputeTitle: "Abrir una disputa",
    disputeHint:
      "El pago queda retenido y el equipo de la comunidad revisa todo lo registrado en la colaboración.",
    disputePlaceholder: "Contanos qué pasó.",
    disputeSent: "Abriste la disputa. El pago queda retenido hasta que se resuelva.",
    frozen: "El pago permanece protegido durante una disputa.",
    creatorWaiting: (deadline: string) =>
      `Entregaste. El negocio tiene hasta el ${deadline} para revisar; si no responde, el pago se libera solo.`,
    approved: "¡Aprobaste la entrega!",
    history: (n: number) => (n === 1 ? "1 entrega" : `${n} entregas`),
    version: (n: number) => `Entrega ${n}`,
  },
  release: {
    title: "Pago liberado",
    approvedTitle: "Trabajo aprobado",
    toCreator: "Para el creador",
    toPlatform: (community: string) => `Para ${community}`,
    timelineApproved: "Trabajo aprobado",
    timelineReleased: "Pago liberado a Stripe",
    timelineBank: "Envío al banco",
    bankProcessing: "Procesando",
    bankHint: "Stripe deposita en la cuenta del creador según su calendario de pagos.",
    receipt: "Ver recibo",
    contractHistory: "Ver contrato e historial",
    blockedCreator:
      "Tu pago está aprobado. Para cobrarlo, configurá tu cuenta de cobro en Stripe: es una sola vez.",
    blockedCreatorCta: "Configurar cobros",
    blockedClient:
      "Aprobaste la entrega. El pago queda retenido hasta que el creador termine de configurar su cuenta de cobro.",
    failed: "La transferencia está demorada. La reintentamos sola cada hora.",
    demo: "Modo demostración: no se movió dinero.",
    approvedAuto: "Se aprobó automáticamente al vencer el período de revisión.",
  },
  disputed: {
    title: "Colaboración en disputa",
    body: "El pago queda retenido mientras el equipo de la comunidad revisa los mensajes, las entregas y el contrato. Te avisamos cuando haya una resolución.",
  },
  canceled: {
    title: "Colaboración cancelada",
    refunded: "El pago se reembolsó a la tarjeta del negocio.",
    refundPending: "El reembolso está en proceso. Lo reintentamos solo hasta que salga.",
    noMoney: "No se movió dinero.",
  },
  rejected: {
    title: "Propuesta rechazada",
    body: "La colaboración no siguió adelante. No se movió dinero.",
  },
  metrics: {
    title: "Métricas de campaña",
    emptyTitle: "Todavía no medimos esta campaña",
    emptyBody:
      "Las vistas, el alcance y los clics viven en las redes donde se publica el contenido, y hoy la plataforma no está conectada a esas cuentas. Cuando lo esté, los números reales aparecen acá.",
    note: "Las métricas no afectan el pago de este contrato.",
  },
  history: {
    title: "Historial",
    empty: "Todavía no hay movimientos.",
    system: "Automático",
    you: "Vos",
  },
  contractSheet: {
    title: "Contrato de colaboración",
    signatures: "Firmas",
  },
  common: {
    cancel: "Cancelar",
    confirm: "Confirmar",
    back: "Volver",
    close: "Cerrar",
  },
} as const;

export const PAYOUT_COPY = {
  title: "Cobros",
  subtitle: "Dónde recibís la plata de tus colaboraciones.",
  intro:
    "Los pagos de las colaboraciones te llegan por Stripe, la misma plataforma que procesa el cobro al negocio. Configurás tu cuenta una sola vez y Stripe deposita en tu banco.",
  statusMissing: "Todavía no configuraste tu cuenta de cobro",
  statusIncomplete: "Tu cuenta de cobro está a medio configurar",
  statusIncompleteBody: "Stripe necesita algunos datos más antes de poder transferirte. Seguí donde dejaste.",
  statusReady: "Tu cuenta de cobro está lista",
  statusReadyBody: "Cuando un negocio apruebe tu trabajo, te transferimos al instante.",
  start: "Configurar cobros con Stripe",
  resume: "Completar configuración",
  dashboard: "Ver mis pagos en Stripe",
  pending: (amount: string, n: number) =>
    n === 1 ? `Tenés ${amount} aprobados esperando que termines la configuración.` : `Tenés ${amount} en ${n} colaboraciones esperando que termines la configuración.`,
  returned: "Volviste de Stripe. Actualizamos el estado de tu cuenta.",
  error: "No pudimos leer tu cuenta de Stripe. Probá de nuevo en un ratito.",
  unavailable: "Los cobros todavía no están habilitados en esta comunidad.",
  notCreator: "Los cobros se configuran desde un perfil de creador.",
  notCreatorCta: "Armar mi perfil de creador",
  needsLogin: "Entrá a tu cuenta para configurar tus cobros.",
  due: (n: number) => (n === 1 ? "Falta 1 dato" : `Faltan ${n} datos`),
  facts: [
    "Stripe verifica tu identidad y tu cuenta bancaria: nosotros no vemos esos datos.",
    "La plataforma se queda con la comisión acordada en cada contrato; el resto es tuyo.",
    "Si todavía no configuraste la cuenta, el pago aprobado queda guardado hasta que lo hagas.",
  ],
} as const;

export const EVENT_COPY: Record<string, string> = {
  proposed: "Propuesta enviada",
  terms_edited: "Propuesta actualizada",
  terms_changes_requested: "Pidió cambios en la propuesta",
  accepted: "Propuesta aceptada — contrato generado",
  rejected: "Propuesta rechazada",
  signed: "Firmó el contrato",
  fully_signed: "Contrato firmado por las dos partes",
  checkout_opened: "Abrió el pago",
  funded: "Pago protegido confirmado",
  payment_orphan_refunded: "Pago fuera de término reembolsado",
  milestone_added: "Sumó un hito",
  milestone_done: "Completó un hito",
  milestone_undone: "Reabrió un hito",
  delivered: "Entregó el trabajo",
  revision_requested: "Pidió una revisión",
  approved: "Aprobó la entrega",
  auto_approved: "Aprobada al vencer la revisión",
  payout_blocked: "Pago retenido: falta la cuenta de cobro",
  payout_failed: "Transferencia demorada",
  released: "Pago liberado al creador",
  disputed: "Abrió una disputa",
  chargeback: "El banco abrió un contracargo",
  canceled: "Canceló la colaboración",
  refunded: "Pago reembolsado",
  template_reset: "Volvió a propuesta para generar el contrato",
};
